apiVersion: v1
kind: Service
metadata:
  name: springdemo-service
spec:
  selector:
    app: {{.Values.appLabel}}
  type: NodePort
  ports: 
  - protocol: TCP
    port: 8090
    targetPort: {{.Values.containerPort}}
    
  