apiVersion: v1
kind: Service
metadata:
  name: springdemo-service
spec:
  selector:
    app: {{.Values.appLabel}}
  type: ClusterIP
  ports: 
  - protocol: TCP
    port: 80
    targetPort: {{.Values.containerPort}}

  